### ISSUE TITLE
Focus should restore proxy settings

### ISSUE THREAD

**Issue by terhorst** [bradjasper/Focus#10]
I think currently the default when "un"-focusing is to reset the auto proxy URL to be blank (actually a single space from looking at the source). It would be very helpful if instead it were restored to whatever it was before Focus overwrote it. My university uses a proxy to grant remote access to journals, so in order to do actual work I need to periodically disable Focus and use the other proxy. (Better still would be to alter the Focus proxy server to pass through any requests that aren't blocked, but this sounds like more work.)

**Comment by bradjasper** [comment]
This shouldn't be an issue anymore with the latest version on the website (https://heyfocus.com).
