### ISSUE TITLE
ERROR [launcher]: Cannot start PhantomJS

### ISSUE THREAD

**Issue by Yeti-or** [bradjasper/Focus#11]
Hello, I have an issue with Phantom.js

When doing smth like this:
``
var page = require("webpage").create();
page.open("http://213.180.218.20:9876/?id=98277431");
``
I don't get response.  Actually, this is code from karma runner (https://github.com/karma-runner/karma-phantomjs-launcher/blob/master/index.js#L46-L47)

at same time opening http://213.180.218.20:9876/ in Chromium seems to be ok.

**Comment by bradjasper** [comment]
This is quite old, but this should be fixed on the paid version on the website (https://heyfocus.com).
