### ISSUE TITLE
Forbidden access page not loaded properly on https blocked url

### ISSUE THREAD

**Issue by lukaspili** [bradjasper/Focus#14]
Hey,
Nothing serious, but when i'm trying to load a blocked page with https url, it does not show the proper page with the random quote, but the chrome standard failure page with error code: ERR_TUNNEL_CONNECTION_FAILED.

Btw, awesome app!
Thanks.

**Comment by bradjasper** [comment]
This is all fixed in the version on https://heyfocus.com
