### ISSUE TITLE
Helper tool won't install

### ISSUE THREAD

**Issue by halbtuerke** [bradjasper/Focus#19]
Hi,

after downloading the source, modifying code signing and fixing compile issues with Sparkle [1], I tried running Focus but there seems to be something wrong with the installation of the helper application.

The first time I tried I was asked repeatedly for an admin password. After providing the password several times with no success I pressed  "Cancel" which led to the following message:

![screen shot 2014-12-15 at 17 08 44](https://cloud.githubusercontent.com/assets/160/5439059/0de6a434-847d-11e4-8499-bb7068fcc05f.png)

Now whenever I try running Focus it asks once for the admin password and the error message immediately shows up.

Anything I'm doing wrong?

Tech Specs:
- OS X 10.10.1 (14B25)
- Xcode 6.1.1 (6A2008a)

[1] The Sparkle framework had to be deleted and readded otherwise the following error occurred:
```
...AppDelegate.m:1:9: fatal error: 'Sparkle/Sparkle.h' file not found
#import <Sparkle/Sparkle.h>
```

**Comment by DaiWenqi** [comment]
> Thanks for the hint. I will have a look at the guide.

你好，这是什么，不懂
