### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Anahkiasen** [bradjasper/Focus#20]
Hey, Focus hasn't been updated in a while, is it still maintained? If not, do you have an alternative app you recommend?

**Comment by bradjasper** [comment]
Hello, Focus is updated all the time, just no longer as an open source
project. The app is available here (https://heyfocus.com). If you're
looking for a free alternative, Self Control for Mac is a good one.

**Comment by Anahkiasen** [comment]
Yeah but Self Control doesn't allow app blocking which is why I love Focus. But if it's still maintained then it's all good for me. :p

Should probably add a note about it in the README. The [changelog too](https://heyfocus.com/changelog/) seems a bit behind (latest is 1.4.1 and changelog says 1.4.0 is still in beta). Keep up the good work!
